### ISSUE TITLE
the code of your team (about another MICCAI21 paper)

### ISSUE THREAD

**Issue by lichen14** [dewenzeng/positional_cl#1]
I would like to congratulate the authors for this outstanding paper!
I am wondering if your team can share the code of another MICCAI21 paper (Federated Contrastive Learning for Volumetric Medical Image Segmentation), both papers will help us a lot for Contrastive Learning in the medical domain. 
thanks.

**Comment by dewenzeng** [comment]
> I would like to congratulate the authors for this outstanding paper! I am wondering if your team can share the code of another MICCAI21 paper (Federated Contrastive Learning for Volumetric Medical Image Segmentation), both papers will help us a lot for Contrastive Learning in the medical domain. thanks.
@lichen14 Thanks for your interest. The code of federated contrastive learning paper is maintained by Yawen (the first author), you can ask him for that. I think he is planning to share that but is not ready yet.
