### ISSUE TITLE
The hyperparameters for HVSMR supervised learning

### ISSUE THREAD

**Issue by gskrpb** [dewenzeng/positional_cl#10]
It puzzles me how this finetuning works since I can only get ~0.67 on M=6 on HVSMR Dataset using ACDC pretrained model.
My settings are:
`--batch_size 4 --epochs 100 --lr 1e-4 --min_lr 5e-6 --initial_filter_size 48 --classes 4 --dataset hvsmr --patch_size 352 352`
Could you please provide me your settings for that?

**Comment by dewenzeng** [comment]
@gskrpb The HVSMR dataset only has 3 classes (background, blood pool, and Myo), maybe you need to set the --classes to 3.
