### ISSUE TITLE
request for dataset after preprocessing

### ISSUE THREAD

**Issue by lichen14** [dewenzeng/positional_cl#2]
Do you mind sharing the dataset after preprocessing? That will help a lot.  : )
Thank you very much, and we will also cite your work.

**Comment by dewenzeng** [comment]
@lichen14 Sure. I can put them on Google Drive and send you the link when it's done.

**Comment by lichen14** [comment]
@dewenzeng, thanks for your help! 👍 
Can you put them on Baidu Netdisk or other places instead of Google Drive? 
For some well-known reasons, accessing Google Drive in Mainland China is not friendly.
Thank you very much!

**Comment by hritam-98** [comment]
Is it possible to have the link of the processed data?

**Comment by dewenzeng** [comment]
@hritam-98 Sorry, I actually do not have the right to share the data, so it would be better if you can get them from the original source.

**Comment by hritam-98** [comment]
Hello,

Actually I was asking for the preprocessed data, I couldn't extract that
using the code, there were some errors.


It would be very helpful if you can share the Google drive link of the
preprocessed data.

Thanks,
Hritam Basak

**Comment by dewenzeng** [comment]
@hritam-98 You can find them here: https://drive.google.com/drive/folders/1IYmqNUB0ZtkwTvCPqMJB5BvvorBjQXfK?usp=sharing. Perhaps you can tell me what errors did you get from doing the preprocessing, cause the data I'm sharing is done using the code in the repo and that works fine.

**Comment by zshyang** [comment]
Hi @dewenzeng ,
The file `chd/supervised/ct_1081/frame038.npz` seems corrupted.

**Comment by dewenzeng** [comment]
Hi @zshyang ,
Sorry about that, I just updated a new file.
