### ISSUE TITLE
question on package import

### ISSUE THREAD

**Issue by yxzhang98** [dewenzeng/positional_cl#6]
Hi, i'm trying to run the code train_supervised.py, there is something wrong with the package metrics. There is no class named SegmentationMetrics when import this package. I would like to ask how this metrics package should be imported, thank you!

**Comment by dewenzeng** [comment]
@yxzhang98 The `SegmentationMetric` class is in the `metrics.py`. Normally, if your `train_supervised.py` is in the same directory as `metrics.py`, you can use `from metrics import SegmentationMetric`. Maybe you should remove the 's'?

**Comment by yxzhang98** [comment]
oh! I see! I missed metric.py in the project for some reasons. thank you
