### ISSUE TITLE
question on fine-tuning

### ISSUE THREAD

**Issue by yxzhang98** [dewenzeng/positional_cl#7]
Hi, I'm trying to run train_supervised.py using acdc dataset. The patchsize used in the pre-training stage is (352,352), as showed in the run_script.sh, the patchsize used in the fine-tuning stage is (512,512) (for chd dataset). I'm wondering what patchsize is selected for acdc dataset, thank you!

**Comment by dewenzeng** [comment]
@yxzhang98 For acdc dataset, the patch size is (352, 352).
